# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {}

modules = []

doc_url = "https://hannesloots.github.io/nbdev-tutorial/"

git_url = "https://github.com/hannesloots/nbdev-tutorial/tree/{branch}/"

def custom_doc_links(name): return None
