# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"Card": "00_card.ipynb"}

modules = ["core.py"]

doc_url = "https://hannesloots.github.io/nbdev_tutorial/"

git_url = "https://github.com/hannesloots/nbdev_tutorial/tree/{branch}/"

def custom_doc_links(name): return None
